var debug = require('debug')

exports.handlers = debug('taskify_server:handlers')
exports.errors = debug('taskify_server:errors')
exports.authentication = debug('taskify_server:authentication')
exports.server = debug('taskify_server:server')
exports.balance = debug('taskify_server:balance')
exports.home = debug('taskify_server:home')
exports.insert = debug('taskify_server:insert')
exports.ledger = debug('taskify_server:ledger')
exports.today = debug('taskify_server:today')
exports.tx = debug('taskify_server:tx')
