var debug = require('debug')

exports.handlers = debug('qpm_basic_income:handlers')
exports.errors = debug('qpm_basic_income:errors')
exports.authentication = debug('qpm_basic_income:authentication')
exports.server = debug('qpm_basic_income:server')
exports.balance = debug('qpm_basic_income:balance')
exports.home = debug('qpm_basic_income:home')
exports.insert = debug('qpm_basic_income:insert')
exports.ledger = debug('qpm_basic_income:ledger')
exports.today = debug('qpm_basic_income:today')
exports.tx = debug('qpm_basic_income:tx')
